--CREATE OR REPLACE VIEW HIERARCHY_PL_TEXTS as
(WITH CTE AS
(
SELECT  *
		  , ROW_NUMBER() OVER () as ROW_NUM
		FROM
			"PL_HIERARCHY"
)
SELECT COLUMN_0 NODE, COLUMN_1 DESC
FROM
	(
	SELECT *, LAG(COLUMN_1) OVER (PARTITION BY A ORDER BY ROW_NUM) as LAG FROM 
		(
		SELECT '' A,"COLUMN_0", "COLUMN_1", ROW_NUM FROM CTE WHERE "COLUMN_0" <> '' UNION ALL
		SELECT '' A,"COLUMN_1", "COLUMN_2", ROW_NUM FROM CTE WHERE "COLUMN_1" <> '' UNION ALL
		SELECT '' A,"COLUMN_2", "COLUMN_3", ROW_NUM FROM CTE WHERE "COLUMN_2" <> '' UNION ALL
		SELECT '' A,"COLUMN_3", "COLUMN_4", ROW_NUM FROM CTE WHERE "COLUMN_3" <> '' UNION ALL
		SELECT '' A,"COLUMN_4", "COLUMN_5", ROW_NUM FROM CTE WHERE "COLUMN_4" <> '' UNION ALL
		SELECT '' A,"COLUMN_5", "COLUMN_6", ROW_NUM FROM CTE WHERE "COLUMN_5" <> '' UNION ALL
		SELECT '' A,"COLUMN_6", "COLUMN_7", ROW_NUM FROM CTE WHERE "COLUMN_6" <> '' UNION ALL
		SELECT '' A,"COLUMN_7", "COLUMN_8", ROW_NUM FROM CTE WHERE "COLUMN_7" <> '' UNION ALL
		SELECT '' A,"COLUMN_8", "COLUMN_9", ROW_NUM FROM CTE WHERE "COLUMN_8" <> '' UNION ALL
		SELECT '' A,"COLUMN_9", "COLUMN_10", ROW_NUM FROM CTE WHERE "COLUMN_9" <> '' UNION ALL
		SELECT '' A,"COLUMN_10", "COLUMN_11", ROW_NUM FROM CTE WHERE "COLUMN_10" <> ''
		)
	)
WHERE COLUMN_0 <> LAG AND COLUMN_1 <> ''
ORDER BY ROW_NUM
);